import { StyleSheet ,Dimensions} from 'react-native';

const styles = StyleSheet.create({
  // Existing styles remain the same, add new styles for connection features:

  // Connection Status Styles
  offlineBadge: {
    backgroundColor: '#e74c3c',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 10,
  },
  offlineBadgeText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  offlineWarning: {
    color: '#e74c3c',
    fontSize: 12,
    marginTop: 10,
    textAlign: 'center',
  },
  connectionBadge: {
    backgroundColor: '#e74c3c',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    marginTop: 5,
    alignSelf: 'flex-start',
  },
  connectionBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  statNoInternet: {
    color: '#f39c12',
  },
  disabledButton: {
    backgroundColor: '#95a5a6',
    opacity: 0.7,
  },
  disabledText: {
    color: '#7f8c8d',
  },
  disabledFab: {
    backgroundColor: '#95a5a6',
  },
  offlineBanner: {
    backgroundColor: '#f39c12',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    alignItems: 'center',
  },
  offlineBannerText: {
    color: 'white',
    textAlign: 'center',
    marginBottom: 10,
  },
  offlineRetryButton: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 6,
  },
  offlineRetryText: {
    color: 'white',
    fontWeight: 'bold',
  },
  printedBadge: {
    color: '#27ae60',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 5,
  },
  offlineNote: {
    color: '#e74c3c',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 5,
  },

  // No Internet Modal Styles
  noInternetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  noInternetModal: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  noInternetIconContainer: {
    marginBottom: 15,
  },
  noInternetIcon: {
    fontSize: 50,
  },
  noInternetTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 10,
    textAlign: 'center',
  },
  noInternetMessage: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 22,
  },
  noInternetDetail: {
    fontSize: 14,
    color: '#95a5a6',
    marginBottom: 20,
  },
  noInternetButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  noInternetButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  noInternetRetryButton: {
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3498db',
  },
  noInternetRetryText: {
    color: '#3498db',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Existing styles continue from your original code...
  loginContainer: {
    flex: 1,
    backgroundColor: '#2c3e50',
  },
  loginContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 30,
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 50,
  },
  loginAppName: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 8,
  },
  loginSubtitle: {
    fontSize: 16,
    color: '#bdc3c7',
    textAlign: 'center',
  },
  loginForm: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
  },
  pinContainer: {
    width: '100%',
    marginBottom: 30,
  },
  pinLabel: {
    fontSize: 14,
    color: '#ecf0f1',
    marginBottom: 10,
    textAlign: 'center',
  },
  pinInputContainer: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 12,
    marginBottom: 10,
    position: 'relative',
    height: 60,
  },
  pinInputError: {
    borderWidth: 2,
    borderColor: '#e74c3c',
  },
  pinInput: {
    fontSize: 18,
    color: '#2c3e50',
    letterSpacing: 20,
    opacity: 0,
  },
  pinDots: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  pinDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ecf0f1',
    marginHorizontal: 8,
  },
  pinDotFilled: {
    backgroundColor: '#3498db',
  },
  errorText: {
    color: '#e74c3c',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 5,
  },
  loginButton: {
    backgroundColor: '#3498db',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 40,
    width: '100%',
    alignItems: 'center',
  },
  loginButtonDisabled: {
    backgroundColor: '#95a5a6',
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  loginFooter: {
    marginTop: 30,
    alignItems: 'center',
  },
  footerText: {
    color: '#95a5a6',
    fontSize: 12,
    marginBottom: 5,
  },
  footerHint: {
    color: '#7f8c8d',
    fontSize: 11,
    textAlign: 'center',
  },
  loginLogo: {
    borderRadius: 50,
    width: 100,
    height: 100,
    marginBottom: 10,
  },
  
  // Dashboard Styles
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  headerLeft: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#7f8c8d',
    marginTop: 2,
  },
  logoutButton: {
    backgroundColor: '#e74c3c',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  logoutText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  statsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 5,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  statConnected: {
    color: '#27ae60',
  },
  statDisconnected: {
    color: '#e74c3c',
  },
  statLabel: {
    fontSize: 11,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    marginHorizontal: 15,
    marginBottom: 15,
    borderRadius: 12,
    paddingHorizontal: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  searchInput: {
    flex: 1,
    height: 50,
    fontSize: 16,
    color: '#2c3e50',
  },
  clearSearch: {
    fontSize: 18,
    color: '#95a5a6',
    paddingHorizontal: 10,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginBottom: 15,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 4,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: '#3498db',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7f8c8d',
  },
  activeTabText: {
    color: '#ffffff',
  },
  tabCount: {
    fontSize: 10,
    color: '#bdc3c7',
    marginTop: 2,
  },
  jobList: {
    flex: 1,
    paddingHorizontal: 15,
  },
  loader: {
    marginTop: 50,
  },
  jobCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  jobCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  jobOrderNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  jobCustomer: {
    fontSize: 14,
    color: '#495057',
    marginTop: 2,
  },
  jobTime: {
    fontSize: 12,
    color: '#7f8c8d',
    marginTop: 2,
  },
  reprintButton: {
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  reprintText: {
    fontSize: 12,
    color: '#3498db',
    fontWeight: '600',
  },
  jobItems: {
    marginBottom: 15,
  },
  jobItemText: {
    fontSize: 14,
    color: '#495057',
    marginBottom: 4,
  },
  moreItemsText: {
    fontSize: 12,
    color: '#6c757d',
    fontStyle: 'italic',
  },
  jobCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e9ecef',
    paddingTop: 15,
  },
  jobTotal: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#27ae60',
  },
  viewReceipt: {
    fontSize: 14,
    color: '#3498db',
    fontWeight: '600',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 50,
  },
  emptyStateTitle: {
    fontSize: 18,
    color: '#6c757d',
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#adb5bd',
    textAlign: 'center',
    marginBottom: 20,
  },
  refreshButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  refreshButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: Dimensions.get('window').height * 0.9,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  modalActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalReprintButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 6,
    marginRight: 15,
  },
  modalReprintText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  closeButton: {
    fontSize: 24,
    color: '#6c757d',
  },
  receiptContent: {
    padding: 20,
  },
  receiptHeader: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  receiptShopName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 10,
  },
  receiptOrderNumber: {
    fontSize: 16,
    color: '#495057',
    marginBottom: 5,
  },
  receiptDate: {
    fontSize: 14,
    color: '#6c757d',
  },
  receiptCustomer: {
    marginBottom: 20,
  },
  receiptSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#495057',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    paddingBottom: 5,
  },
  customerName: {
    fontSize: 18,
    color: '#2c3e50',
    marginTop: 5,
  },
  receiptItems: {
    marginBottom: 20,
  },
  receiptItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f8f9fa',
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    color: '#495057',
    marginBottom: 2,
  },
  itemQuantity: {
    fontSize: 12,
    color: '#6c757d',
  },
  itemPrice: {
    fontSize: 14,
    color: '#6c757d',
    marginHorizontal: 10,
    width: 60,
  },
  itemSubtotal: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2c3e50',
    width: 70,
    textAlign: 'right',
  },
  receiptTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 2,
    borderTopColor: '#495057',
    paddingTop: 15,
    marginBottom: 20,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#495057',
  },
  totalAmount: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#27ae60',
  },
  receiptNotes: {
    marginBottom: 20,
  },
  noteText: {
    fontSize: 14,
    color: '#6c757d',
    marginBottom: 5,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#3498db',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  fabText: {
    fontSize: 24,
    color: '#ffffff',
  },
});

export default styles;
